AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  NGSL API

  Next Generation Service Layer for the EFM Enterprise Data Warehouse

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 2048

Resources:
  CustomersReadById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cvms/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        CustomersGetByIdAPI:
          Type: Api
          Properties:
            Path: /cvms/customers/{id}
            Method: GET
            Auth:
              Authorizer: NONE

  VehiclesReadById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cvms/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        VehiclesGetByIdAPI:
          Type: Api
          Properties:
            Path: /cvms/vehicles/{id}
            Method: GET
            RequestParameters:
                - method.request.querystring.idtype:
                     Required: true
            Auth:
              Authorizer: NONE
