AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ServerlessApi-Sql

  Sample SAM Template for ServerlessApi-Sql

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 2048

Resources:
  ToDoItemsRead:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: reports/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        ToDoItemsGetAPI:
          Type: Api
          Properties:
            Path: /reports/todoitems
            Method: GET
            Auth:
              Authorizer: NONE

  ToDoItemsReadById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: reports/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        ToDoItemsGetAPI:
          Type: Api
          Properties:
            Path: /reports/todoitems/{Id}
            Method: GET
            Auth:
              Authorizer: NONE

  LocationsRead:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: reports/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        ToDoItemsGetAPI:
          Type: Api
          Properties:
            Path: /reports/locations
            Method: GET
            Auth:
              Authorizer: NONE

  LocationsReadById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: reports/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        ToDoItemsGetAPI:
          Type: Api
          Properties:
            Path: /reports/locations/{Id}
            Method: GET
            Auth:
              Authorizer: NONE

  UsersRead:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: reports/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        ToDoItemsGetAPI:
          Type: Api
          Properties:
            Path: /reports/users
            Method: GET
            Auth:
              Authorizer: NONE

  UsersReadById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: reports/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        ToDoItemsGetAPI:
          Type: Api
          Properties:
            Path: /reports/users/{Id}
            Method: GET
            Auth:
              Authorizer: NONE

